// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VShop.ProductApi.Context;

#nullable disable

namespace VShop.ProductApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VShop.ProductApi.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Eletrônicos"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Informática"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Acessórios"
                        });
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<long>("Stock")
                        .HasColumnType("bigint");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 2,
                            Description = "Notebook Intel Core i5, 16GB RAM, SSD 512GB",
                            ImageUrl = "notebook-dell.jpg",
                            Name = "Notebook Dell Inspiron",
                            Price = 4299.90m,
                            Stock = 15L
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 3,
                            Description = "Mouse Gamer RGB 8000 DPI",
                            ImageUrl = "mouse-g203.jpg",
                            Name = "Mouse Gamer Logitech G203",
                            Price = 149.90m,
                            Stock = 50L
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Description = "Switch Blue ABNT2",
                            ImageUrl = "kumara.jpg",
                            Name = "Teclado Mecânico Redragon Kumara",
                            Price = 279.90m,
                            Stock = 35L
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            Description = "256GB, 12GB RAM",
                            ImageUrl = "galaxy-s25.jpg",
                            Name = "Smartphone Samsung Galaxy S25",
                            Price = 5299.90m,
                            Stock = 20L
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Monitor IPS Full HD",
                            ImageUrl = "lg-ultrawide.jpg",
                            Name = "Monitor LG UltraWide 29\"",
                            Price = 1299.90m,
                            Stock = 12L
                        });
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Product", b =>
                {
                    b.HasOne("VShop.ProductApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VShop.ProductApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
